/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomerForm: typeof import('./src/components/CustomerForm.vue')['default']
    CustomerMap: typeof import('./src/components/CustomerMap.vue')['default']
    ProductForm: typeof import('./src/components/ProductForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
